package com.playbox.games.ui.arithmetic

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.playbox.games.ui.dictation.DictationModel
import com.playbox.games.ui.dictation.RecognizedUtterance
import com.playbox.games.util.SpokenNumberParser
import java.nio.ByteBuffer
import java.nio.ByteOrder
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import org.vosk.Model
import org.vosk.Recognizer

/**
 * Feeds synthesised Chinese utterances straight into the bundled Vosk model on a real device,
 * which is the only way to prove that the shipped model, the number grammar and the answer parser
 * really agree with each other.
 *
 * The audio files are 16 kHz mono PCM generated by `tools/generate-speech-samples.sh`.
 */
@RunWith(AndroidJUnit4::class)
class DictationRecognitionTest {

    private val numbers = mapOf(
        "n0.wav" to 0,
        "n4.wav" to 4,
        "n5.wav" to 5,
        "n7.wav" to 7,
        "n10.wav" to 10,
        "n12.wav" to 12,
        "n15.wav" to 15,
        "n23.wav" to 23,
        "n38.wav" to 38,
        "n60.wav" to 60,
        "n99.wav" to 99,
        "n100.wav" to 100,
    )

    /** Everyday phrases a child might say instead of an answer; none of them is a number. */
    private val nonNumbers = listOf(
        "not-a-number.wav",
        "noise-unknown.wav",
        "noise-mother.wav",
        "noise-question.wav",
    )

    @Test
    fun recognisesSpokenNumbersWithTheNumberGrammar() {
        withRecognizer { recognizer ->
            val failures = mutableListOf<String>()
            numbers.forEach { (file, expected) ->
                val utterance = recognize(recognizer, readSamples(file))
                val parsed = SpokenNumberParser.parse(utterance.text)
                if (parsed != expected || !utterance.isNumber) {
                    failures += "$file expected=$expected heard='${utterance.text}' parsed=$parsed"
                }
            }
            if (failures.isNotEmpty()) {
                throw AssertionError("misrecognised: " + failures.joinToString("; "))
            }
        }
    }

    @Test
    fun filtersOutSpeechThatIsNotANumber() {
        withRecognizer { recognizer ->
            val judged = mutableListOf<String>()
            nonNumbers.forEach { file ->
                val utterance = recognize(recognizer, readSamples(file))
                // Without [unk] in the grammar every phrase would be forced into number words and
                // would end up judged as a wrong answer.
                if (utterance.isNumber) judged += "$file decoded as '${utterance.text}'"
            }
            if (judged.isNotEmpty()) {
                throw AssertionError("non-number speech was treated as an answer: " + judged.joinToString("; "))
            }
        }
    }

    private inline fun withRecognizer(block: (Recognizer) -> Unit) {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val modelDirectory = DictationModel.prepare(context)
        val model = Model(modelDirectory.absolutePath)
        try {
            val recognizer = Recognizer(model, DictationModel.SampleRate, DictationModel.numberGrammarJson())
            try {
                block(recognizer)
            } finally {
                recognizer.close()
            }
        } finally {
            model.close()
        }
    }

    private fun recognize(recognizer: Recognizer, pcm: ByteArray): RecognizedUtterance {
        recognizer.acceptWaveForm(pcm, pcm.size)
        // The trailing silence of the sample is too short to trigger an endpoint, so the final
        // result is what carries the utterance.
        return DictationModel.parseUtterance(recognizer.finalResult)
    }

    private fun readSamples(name: String): ByteArray {
        // The audio lives in the test APK, not in the app under test.
        val assets = InstrumentationRegistry.getInstrumentation().context.assets
        return pcmFromWave(assets.open("numbers/$name").use { it.readBytes() })
    }

    /** Strips the RIFF header and returns the raw PCM payload. */
    private fun pcmFromWave(bytes: ByteArray): ByteArray {
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        var index = 12
        while (index + 8 <= bytes.size) {
            val id = String(bytes, index, 4, Charsets.US_ASCII)
            val size = buffer.getInt(index + 4)
            if (id == "data") {
                return bytes.copyOfRange(index + 8, minOf(index + 8 + size, bytes.size))
            }
            index += 8 + size + (size and 1)
        }
        throw AssertionError("wave file has no data chunk")
    }
}
