package com.playbox.games.ui.pinyin

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.playbox.games.ui.dictation.DictationModel
import com.playbox.games.ui.dictation.RecognizedUtterance
import com.playbox.games.util.PinyinSyllable
import com.playbox.games.util.isCorrectReading
import com.playbox.games.util.pinyinCardGrammarJson
import java.nio.ByteBuffer
import java.nio.ByteOrder
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import org.vosk.Model
import org.vosk.Recognizer

/**
 * Reads synthesised syllable audio through the bundled model with the same deck grammar the app
 * uses, proving that a syllable read aloud lands back on the right card.
 *
 * The audio files are 16 kHz mono PCM generated by `tools/generate-speech-samples.sh`.
 */
@RunWith(AndroidJUnit4::class)
class PinyinRecognitionTest {

    /** A small round, exactly like the tool would build. */
    private val deck = listOf(
        PinyinSyllable("ma", "mā", "妈"),
        PinyinSyllable("ba", "bā", "八"),
        PinyinSyllable("shu", "shū", "书"),
        PinyinSyllable("chi", "chī", "吃"),
    )

    private val samples = mapOf(
        "ma.wav" to "ma",
        "ba.wav" to "ba",
        "shu.wav" to "shu",
        "chi.wav" to "chi",
    )

    @Test
    fun spokenSyllablesLandOnTheMatchingCard() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val modelDirectory = DictationModel.prepare(context)
        val model = Model(modelDirectory.absolutePath)
        try {
            val failures = mutableListOf<String>()
            // Each card is verified with its own one-word vocabulary, exactly like the tool does.
            deck.forEach { syllable ->
                val recognizer = Recognizer(model, DictationModel.SampleRate, pinyinCardGrammarJson(syllable))
                try {
                    val utterance = recognize(recognizer, readSample("${syllable.plain}.wav"))
                    if (!isCorrectReading(utterance.text, syllable)) {
                        failures += "${syllable.plain} heard='${utterance.text}'"
                    }
                } finally {
                    recognizer.close()
                }
            }
            if (failures.isNotEmpty()) {
                throw AssertionError("misheard syllables: " + failures.joinToString("; "))
            }
        } finally {
            model.close()
        }
    }

    private fun recognize(recognizer: Recognizer, pcm: ByteArray): RecognizedUtterance {
        recognizer.acceptWaveForm(pcm, pcm.size)
        return DictationModel.parseUtterance(recognizer.finalResult)
    }

    private fun readSample(name: String): ByteArray {
        val assets = InstrumentationRegistry.getInstrumentation().context.assets
        return pcmFromWave(assets.open("zimu/$name").use { it.readBytes() })
    }

    private fun pcmFromWave(bytes: ByteArray): ByteArray {
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        var index = 12
        while (index + 8 <= bytes.size) {
            val id = String(bytes, index, 4, Charsets.US_ASCII)
            val size = buffer.getInt(index + 4)
            if (id == "data") return bytes.copyOfRange(index + 8, minOf(index + 8 + size, bytes.size))
            index += 8 + size + (size and 1)
        }
        throw AssertionError("wave file has no data chunk")
    }
}
